### Numpy Mathematical & Statistical Functions:-

In [21]:
import numpy as np

In [29]:
a = np.arange(20).reshape(5,4)
b = np.arange(10,30).reshape(5,4)
print(a)
print("\n",b)
print("Max:",np.max(a))
print("Sum:",np.sum(a))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
Max: 19
Sum: 190


In [23]:
print("Max:",np.max(a,axis=0))  # Max -> Row-wise
print("Max:",np.max(a,axis=1))  # Max -> Column-wise

Max: [16 17 18 19]
Max: [ 3  7 11 15 19]


In [24]:
print("Sum:",np.sum(a,axis=0))   # Sum -> Column-wise
print("Sum:",np.sum(a,axis=1))   # Sum -> Row-wise

Sum: [40 45 50 55]
Sum: [ 6 22 38 54 70]


In [25]:
print("Mean:",np.mean(a,axis=0))  # Mean -> Column-wise
print("Mean:",np.mean(a,axis=1))  # Mean -> Row-wise

Mean: [ 8.  9. 10. 11.]
Mean: [ 1.5  5.5  9.5 13.5 17.5]


In [26]:
print("Median:",np.median(b,axis=0))  
print("Median:",np.median(b,axis=1))  

Median: [18. 19. 20. 21.]
Median: [11.5 15.5 19.5 23.5 27.5]


In [27]:
print("Standard Deviation:",np.std(a,axis=0))  
print("Standard Deviation:",np.std(b,axis=1))  

Standard Deviation: [5.65685425 5.65685425 5.65685425 5.65685425]
Standard Deviation: [1.11803399 1.11803399 1.11803399 1.11803399 1.11803399]
