**"Sorting Methods":-**

In [1]:
import numpy as np

In [2]:
x = np.array([[12,34,63,672,8],[3,6,80,22,100]])
print(x)
y = np.ndarray.sort(x)
print(x)

[[ 12  34  63 672   8]
 [  3   6  80  22 100]]
[[  8  12  34  63 672]
 [  3   6  22  80 100]]


In [3]:
x = np.array([10,35,61,50,18])
print("Original(x):",x)
y = np.sort(x)
print("Sorted:",y)                # Sorting in 'Ascending Order'

print("Sorted:",np.sort(x)[::-1]) # Sorting in 'Descending Order'
print("Original(x):",x)

Original(x): [10 35 61 50 18]
Sorted: [10 18 35 50 61]
Sorted: [61 50 35 18 10]
Original(x): [10 35 61 50 18]


In [4]:
a = np.array([[41,70,13,80,48],[51,33,42,89,10]])
print("Original(a):\n",a)
b = np.sort(a)
print("Sorted:\n",b)         # It will sort 'Row-wise'
print("Original(a):\n",a)

Original(a):
 [[41 70 13 80 48]
 [51 33 42 89 10]]
Sorted:
 [[13 41 48 70 80]
 [10 33 42 51 89]]
Original(a):
 [[41 70 13 80 48]
 [51 33 42 89 10]]


In [5]:
a = np.array([4,72,12,80,44])
print("Original(a):",a)
b = np.argsort(a)
print("Sorting Indices:",b)
print("Original(a):",a)

Original(a): [ 4 72 12 80 44]
Sorting Indices: [0 2 4 1 3]
Original(a): [ 4 72 12 80 44]


In [6]:
a = np.array([[2,4,7,1],[9,11,5,3]])
print("Original(a):\n",a)
b = np.argsort(a)
print("Sorting Indices:\n",b)         # It will sort 'Row-wise'
print("Original(a):\n",a)

Original(a):
 [[ 2  4  7  1]
 [ 9 11  5  3]]
Sorting Indices:
 [[3 0 1 2]
 [3 2 0 1]]
Original(a):
 [[ 2  4  7  1]
 [ 9 11  5  3]]


In [7]:
a = np.array([[[4,72,12,80,44],[34,77,11,8,9]],[[1,21,87,90,50],[5,4,42,89,1000]]])
print("Original(a):\n",a)
b = np.argsort(a)
print("Sorting Indices:\n",b)   # It will sort 'Row-wise'
print("Original(a):\n",a)

Original(a):
 [[[   4   72   12   80   44]
  [  34   77   11    8    9]]

 [[   1   21   87   90   50]
  [   5    4   42   89 1000]]]
Sorting Indices:
 [[[0 2 4 1 3]
  [3 4 2 0 1]]

 [[0 1 4 2 3]
  [1 0 2 3 4]]]
Original(a):
 [[[   4   72   12   80   44]
  [  34   77   11    8    9]]

 [[   1   21   87   90   50]
  [   5    4   42   89 1000]]]


**"Unique Function:-**

In [8]:
p = np.array([10,66,20,30,10,20,15,20,11,88])
print("Unique function Output:-",np.unique(p))

Unique function Output:- [10 11 15 20 30 66 88]
