## Indexing and Slicing:-

In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4,5])
print("Output:",A[3])

Output: 4


In [3]:
x = np.array([[1,2,3,4],[9,11,5,3]])
print("Original:\n",x)
print("Output:",x[1,2])
print("Output:",x[1])
print("Output:\n",x[:,:])
print("Output:\n",x[:,1:3])

Original:
 [[ 1  2  3  4]
 [ 9 11  5  3]]
Output: 5
Output: [ 9 11  5  3]
Output:
 [[ 1  2  3  4]
 [ 9 11  5  3]]
Output:
 [[ 2  3]
 [11  5]]


In [4]:
a = np.arange(48).reshape(3,4,4)
print("Original:\n",a)
print("Output:\n",a[0:,0:3,1:3])

Original:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
Output:
 [[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[17 18]
  [21 22]
  [25 26]]

 [[33 34]
  [37 38]
  [41 42]]]


In [5]:
arr = np.array([1,2,3,4,5,6,7])        
print("Length of array:",len(arr))
print(arr[1:5])
print(arr[4:])                    # "SLICING"
print(arr[:4])                    
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])
print(arr[1::2])

Length of array: 7
[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[2 4 6]


In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original:\n",arr2)
print("Output:\n",arr2[1,1:4])
print("Output:\n",arr2[0:2,2])
print("Output:\n",arr2[0:2,1:4])
print("Output:\n",arr2[::-1])
print("Output:\n",arr2[::,::2])

Original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Output:
 [7 8 9]
Output:
 [3 8]
Output:
 [[2 3 4]
 [7 8 9]]
Output:
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Output:
 [[ 1  3  5]
 [ 6  8 10]]


In [7]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8,],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(arr3.shape)
print("Original:\n",arr3)
print("Output:\n",arr3[:,:,:1])
print("Output:\n",arr3[:,1:,::2])
print("Output:\n",arr3[:,2])
print("Output:\n",arr3[0:2,-3:-2,-4:-1])

(2, 3, 4)
Original:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Output:
 [[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]
Output:
 [[[ 5  7]
  [ 9 11]]

 [[17 19]
  [21 23]]]
Output:
 [[ 9 10 11 12]
 [21 22 23 24]]
Output:
 [[[ 1  2  3]]

 [[13 14 15]]]
