**Splitting Array:-**

In [1]:
import numpy as np

In [2]:
arr  =np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
arr  =np.array([1,2,3,4,5,6])
print(np.array_split(arr,4))
print(np.array_split(arr,7))

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [4]:
arr  =np.array([1,2,3,4,5,6])
newArr = np.array_split(arr,3)
print(newArr[0])
print(newArr[1])
print(newArr[2])

[1 2]
[3 4]
[5 6]


In [5]:
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(np.shape(a))
print(np.array_split(arr,3))
print("\n",np.split(a,3))
print("V Split:\n",np.vsplit(a,2))
print("H Split:\n",np.hsplit(a,2))

(6, 2)
[array([1, 2]), array([3, 4]), array([5, 6])]

 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
V Split:
 [array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]
H Split:
 [array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [6]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(x)
print("Axis1:",np.array_split(x,3,axis=1))
print("Axis0:",np.array_split(x,3,axis=0))
print("V Split:\n",np.vsplit(x,3))
print("H Split:\n",np.hsplit(x,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Axis1: [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
Axis0: [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
V Split:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
H Split:
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [7]:
p = np.arange(1,19).reshape(3,2,3)
print(p)
print(np.array_split(p,3,axis=0))
print(np.array_split(p,3,axis=1))
print(np.dsplit(p,[2,3]))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]]), array([[[13, 14, 15],
        [16, 17, 18]]])]
[array([[[ 1,  2,  3]],

       [[ 7,  8,  9]],

       [[13, 14, 15]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]],

       [[16, 17, 18]]]), array([], shape=(3, 0, 3), dtype=int32)]
[array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]],

       [[15],
        [18]]]), array([], shape=(3, 2, 0), dtype=int32)]
