## Concatenating Arrays

In [1]:
import numpy as np

In [2]:
a = np.arange(1,5)
b = np.arange(6)
c = np.zeros(10)
print(np.concatenate((a,b),out =c))
print(c)

[1. 2. 3. 4. 0. 1. 2. 3. 4. 5.]
[1. 2. 3. 4. 0. 1. 2. 3. 4. 5.]


In [3]:
A = np.arange(1,5)
B = np.arange(8)
print(np.concatenate((A,B)))
print(A)

[1 2 3 4 0 1 2 3 4 5 6 7]
[1 2 3 4]


In [4]:
x = np.array([[1,2],[3,4]])
y = np.array([[10,50]])
print(np.concatenate((x,y),axis=0))
print(np.concatenate((x,y.T),axis=1))


[[ 1  2]
 [ 3  4]
 [10 50]]
[[ 1  2 10]
 [ 3  4 50]]


In [5]:
p = np.arange(1,25,2).reshape(2,3,2)
q = np.arange(2,14,1).reshape(2,3,2)
print(p) , print(q)

[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]]
[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]]]


(None, None)

In [6]:
print(np.concatenate((p,q),axis=0))

[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]

 [[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]]]


In [7]:
print(np.concatenate((p,q),axis=1))

[[[ 1  3]
  [ 5  7]
  [ 9 11]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[13 15]
  [17 19]
  [21 23]
  [ 8  9]
  [10 11]
  [12 13]]]
