**Joining Arrays:-**

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,3,5,7,9])
a2 = np.array([2,4,6,8,10])
print("Concatenated:",np.concatenate((a1,a2)))
print(np.stack((a1,a2),axis=0))
print(np.stack((a1,a2),axis=1))

Concatenated: [ 1  3  5  7  9  2  4  6  8 10]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [3]:
print("H Stack:",np.hstack((a1,a2)))      # Stacking along 'Rows'
print("V Stack:\n",np.vstack((a1,a2)))    # Stacking along 'Colummn'
print("D Stack:\n",np.dstack((a1,a2)))    # Stacking along 'Height'

H Stack: [ 1  3  5  7  9  2  4  6  8 10]
V Stack:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
D Stack:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]


In [4]:
x = np.arange(1,25,2).reshape(3,4)
y = np.arange(2,26,2).reshape(3,4)
print("Array x:\n",x)
print("Array y:\n",y)
print("Concatenated:\n",np.concatenate((x,y),axis=1))
print("H stack:\n",np.hstack((x,y)))
print("D stack:\n",np.dstack((x,y)))

Array x:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
Array y:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Concatenated:
 [[ 1  3  5  7  2  4  6  8]
 [ 9 11 13 15 10 12 14 16]
 [17 19 21 23 18 20 22 24]]
H stack:
 [[ 1  3  5  7  2  4  6  8]
 [ 9 11 13 15 10 12 14 16]
 [17 19 21 23 18 20 22 24]]
D stack:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
