In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
b =np.array([121,43,2312,112,34,65,74,76,23,7,3278,34,10,6,12,86,66,100])
b.size

18

In [4]:
b.reshape(6,3)

array([[ 121,   43, 2312],
       [ 112,   34,   65],
       [  74,   76,   23],
       [   7, 3278,   34],
       [  10,    6,   12],
       [  86,   66,  100]])

In [5]:
c =np.array([122,43,12,112,3,65,74,7,23,7,328,34,120,6,12,8,6,100])
np.argsort(c)          # Gives the order of indices to sort the Array.

array([ 4, 16, 13,  7,  9, 15,  2, 14,  8, 11,  1,  5,  6, 17,  3, 12,  0,
       10], dtype=int64)

In [6]:
print(np.argmin(c))    # Gives index of smallest element.
print(np.argmax(c))    # Gives index of largest element.

4
10


In [7]:
d =np.array([12,34,45,54,65,34,23,56,330,123])
d.size

10

In [8]:
d =d.reshape(5,2)
print(d)

[[ 12  34]
 [ 45  54]
 [ 65  34]
 [ 23  56]
 [330 123]]


In [9]:
d.argsort(axis=0)    # Sorts the elements "Column-wise"

array([[0, 0],
       [3, 2],
       [1, 1],
       [2, 3],
       [4, 4]], dtype=int64)

In [10]:
d.argsort(axis=1)    # Sorts the elements "Row-wise"

array([[0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0]], dtype=int64)