In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
b = np.swapaxes(a,1,2)
b

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [4]:
b = np.swapaxes(a,0,2)
b

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [5]:
b = np.swapaxes(a,0,1)
b

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [6]:
np.__version__               # To check version of Numpy

'1.26.2'

In [7]:
a =np.array([1,2,3,4,5,6])   # 'List' as an array
print(a)                    
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
a =np.array((1,2,3,4,5,6))   # 'Tuple' as an array
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
a =np.array(('1','2','3','4','5','6'))   # 'String' as an array
print(a)
print(type(a))

['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>


In [10]:
a =np.array({1:1,2:4,3:9,4:16,5:25})    # 'Dictionary' as an array
print(a)
print(type(a))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
<class 'numpy.ndarray'>


In [11]:
a =np.array({1,2,3,4,5,6})   # 'Set' as an array
print(a)
print(type(a))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>
