In [1]:
import numpy as np

In [2]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
lspace = np.linspace(1,50,10)    
lspace           # Gives an Array of equally spaced 10 elements in range(1-50)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [4]:
emp = np.empty((4,3))
emp              # Gives an Array with random elements

array([[1.14644418e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 2.57894000e-057],
       [2.10682847e-076, 5.44114285e-062, 3.92663659e-033],
       [3.73479298e-033, 1.43968400e+160, 1.78740734e-051]])

In [5]:
emp_like = np.empty_like(lspace)
emp_like

array([1.14644418e-311, 3.16202013e-322, 1.11260619e-306, 2.57894000e-057,
       2.10682847e-076, 5.44114285e-062, 3.92663659e-033, 3.73479298e-033,
       1.43968400e+160, 1.78740734e-051])

In [6]:
ide = np.identity(4)     # Gives an 'Identity Matrix'
print(ide)
print(ide.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [7]:
arr = np.arange(30)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)


In [8]:
arr =arr.reshape(3,10)     # Return an Array containing same data with a new shape
print(arr)
print(arr.shape)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
(3, 10)


In [9]:
arr = arr.ravel()          # Return a flattened array
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)


In [10]:
a = np.array([[1,2,3],[4,5,6],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [11]:
for item in a:      
    print(item)

[1 2 3]
[4 5 6]
[10 11 12]


In [12]:
for item in a.flat:       # Using 'flat' to print elements of Array.
    print(item)

1
2
3
4
5
6
10
11
12


In [13]:
a.ndim       # Gives the no. of Dimensions of Array

2

In [14]:
a.nbytes     # Gives the total memory usage of Array

36