## Arithmetic Operations on Numpy Array

In [18]:
import numpy as np

In [19]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[2,2,3],[4,7,9]])
C = a1 + a2
D = a1 - a2
E = a1 * a2      # Multiplication

print(C) , print(D) ,print(E)

[[ 3  4  6]
 [ 8 12 15]]
[[-1  0  0]
 [ 0 -2 -3]]
[[ 2  4  9]
 [16 35 54]]


(None, None, None)

In [20]:
F = a1 ** a2    # Exponentiation
G = a1 / a2     # Division
H = a1 // a2    # Floor Division
I = a1 % a2     # Modulus

print(F) , print(G) ,print(H) , print(I)

[[       1        4       27]
 [     256    78125 10077696]]
[[0.5        1.         1.        ]
 [1.         0.71428571 0.66666667]]
[[0 1 1]
 [1 0 0]]
[[1 0 0]
 [0 5 6]]


(None, None, None, None)

In [21]:
a1 = np.array([[1,2],[4,5]])
a2 = np.array([[2,2,3],[4,7,9]])
J= a1 @ a2          # Matrix Multiplication
print(J)

[[10 16 21]
 [28 43 57]]


In [22]:
print(a1.transpose())
print(a2.transpose())

[[1 4]
 [2 5]]
[[2 4]
 [2 7]
 [3 9]]


## Boolean Indexing

In [41]:
a = np.arange(20,40,2)
print(a)
print(a[a>25])
print(a>30)

[20 22 24 26 28 30 32 34 36 38]
[26 28 30 32 34 36 38]
[False False False False False False  True  True  True  True]


In [28]:
x = np.array([[1,10,3],[4,5,36],[1,56,20]])
print(x % 2 ==0)

[[False  True False]
 [ True False  True]
 [False  True  True]]


In [32]:
p = np.arange(20,30,2)
print(p)
q = [True , False ,True , False , True]
print(p[q])        # It will return the element which position is TRUE

[20 22 24 26 28]
[20 24 28]


In [40]:
X = np.arange(20,40,2).reshape(5,2)
print(X)
Y = [True , False ,True , False , True]
print('\t')
print(X[Y])        # It will work Row-wise

[[20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]]
	
[[20 22]
 [28 30]
 [36 38]]
