**Copy vs View:-**

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
x = arr.copy()
arr[0]=88
x[2]= 77
print(arr)
print(x)

[1 2 3 4 5]
[88  2  3  4  5]
[ 1  2 77  4  5]


In [7]:
A = np.array([1,2,3,4,5])
print(A)
y = A.view()
A[0]=88
y[2]= 77
print(A)
print(y)

[1 2 3 4 5]
[88  2 77  4  5]
[88  2 77  4  5]


**Flattening the array:-**

In [8]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.reshape(-1))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


**Iterating Array:-**

In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    print(x)

print("Output:")
for x in arr:
    for y in x:
        print(y)

print("Output:")
for x in np.nditer(arr):
    print(x)

print("Output:")
for x in np.nditer(arr[:,::2]):
    print(x)



[1 2 3 4]
[5 6 7 8]
Output:
1
2
3
4
5
6
7
8
Output:
1
2
3
4
5
6
7
8
Output:
1
3
5
7


In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

print("Output:")
for x in arr:
    for y in x:
        for z in y:
            print(z)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Output:
1
2
3
4
5
6
7
8
9
10
11
12
