In [1]:
import numpy as np

In [2]:
l1 = [1,2.2,3,4,5,6]
l2 = [1,'2',3,4,5,6]
a1 =np.array(l1)
a2 =np.array(l2)
print(a1)  , print(a2)

[1.  2.2 3.  4.  5.  6. ]
['1' '2' '3' '4' '5' '6']


(None, None)

In [3]:
list1 = [1,'2',3.0,4,5,6]
list2 = [1,'2',3.3,4,5,6]
x =np.array(list1,dtype=float)
y =np.array(list2,dtype='U32')
print(x)  , print(y)

[1. 2. 3. 4. 5. 6.]
['1' '2' '3.3' '4' '5' '6']


(None, None)

In [4]:
A = np.zeros((2,2,3))
A

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
B = np.ones((2,2,3))
B

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Attributes of Numpy Array

In [6]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1.5,2,3],[4,5,6],[7,8,9]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)
print(arr2)
print(arr3)


[1 2 3 4 5 6]
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
print("Dimension:",arr1.ndim)
print("Dimension:",arr2.ndim)
print("Dimension:",arr3.ndim)

Dimension: 1
Dimension: 2
Dimension: 3


In [8]:
print("Shape:",arr1.shape)
print("Shape:",arr2.shape)
print("Shape:",arr3.shape)

Shape: (6,)
Shape: (3, 3)
Shape: (2, 2, 3)


In [9]:
print("Size:",arr1.size)
print("Size:",arr2.size)
print("Size:",arr3.size)

Size: 6
Size: 9
Size: 12


In [10]:
print("Datatype:",arr1.dtype)
print("Datatype:",arr2.dtype)
print("Datatype:",arr3.dtype)

Datatype: int32
Datatype: float64
Datatype: int32


In [11]:
print("Itemsize:",arr1.itemsize)
print("Itemsize:",arr2.itemsize)
print("Itemsize:",arr3.itemsize)

Itemsize: 4
Itemsize: 8
Itemsize: 4
