In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [3]:
arr1.sum(axis=0)      # Summing the elements "Column-wise"

array([5, 7, 9])

In [4]:
arr1.sum(axis=1)      # Summing the elements "Row-wise"

array([ 6, 15])

In [5]:
b = np.array([[7,8,9],[2,8,0]])
print(b)

[[7 8 9]
 [2 8 0]]


In [6]:
b =b.transpose()
# b.T             Transposing an array

In [7]:
arr1.dot(b)        # Finding the 'Dot product'

array([[ 50,  18],
       [122,  48]])

In [8]:
len(dir(np))

591

In [9]:
b = b.T
np.cross(arr1,b)     # Finding the 'Cross Product'

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [10]:
print(b)
np.sort(b)           # Sorting an Array(Row-wise)

[[7 8 9]
 [2 8 0]]


array([[7, 8, 9],
       [0, 2, 8]])

In [11]:
np.sort(b,axis=0)    # Sorting an Array(Column-wise)

array([[2, 8, 0],
       [7, 8, 9]])

In [12]:
x = np.array([ [1, 23, 34, 54, 656, 76, 7],
    [123, 456, 76, 8, 8, 3, 43],  
    [7853, 23, 1, 767, 23, 24, 65] ])
np.sort(x)

array([[   1,    7,   23,   34,   54,   76,  656],
       [   3,    8,    8,   43,   76,  123,  456],
       [   1,   23,   23,   24,   65,  767, 7853]])

In [13]:
%time
np.sort(x , axis=0,kind ='mergesort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[   1,   23,    1,    8,    8,    3,    7],
       [ 123,   23,   34,   54,   23,   24,   43],
       [7853,  456,   76,  767,  656,   76,   65]])