**Numpy "Insertion":-**

In [1]:
import numpy as np

In [2]:
a = np.arange(1,11)
print("Original:",a)

print("Modified:",np.insert(a,1,55))
c = np.insert(a,1,75.8)
print("Modified:",c)

print("Modified:",np.insert(a,(1,3,5),88))    # Inserting single value on multiple indices
print("Original:",a)

Original: [ 1  2  3  4  5  6  7  8  9 10]
Modified: [ 1 55  2  3  4  5  6  7  8  9 10]
Modified: [ 1 75  2  3  4  5  6  7  8  9 10]
Modified: [ 1 88  2  3 88  4  5 88  6  7  8  9 10]
Original: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
w = np.array([[2,4,7,1],[9,11,5,3]])
x = np.insert(w,1,23,axis=0)
y = np.insert(w,1,[23,71,88,99],axis=0)      # Inserting distinct values on single index
z = np.insert(w,(0,2),[30,66,20,77],axis=0)  # Inserting distinct values on multiple indices
print("Original:\n",w)
print("Modified:\n",x)
print("Modified:\n",y)
print("Modified:\n",z)

Original:
 [[ 2  4  7  1]
 [ 9 11  5  3]]
Modified:
 [[ 2  4  7  1]
 [23 23 23 23]
 [ 9 11  5  3]]
Modified:
 [[ 2  4  7  1]
 [23 71 88 99]
 [ 9 11  5  3]]
Modified:
 [[30 66 20 77]
 [ 2  4  7  1]
 [ 9 11  5  3]
 [30 66 20 77]]


In [4]:
x = np.array([[2,4,7,1],[9,11,5,3]])
y = np.insert(x,1,[100,200],axis=1)
z = np.insert(x,(2,3),[101,202],axis=1)
print("Original:\n",x)
print("Modified:\n",y)
print("Modified:\n",z)
print("Modified:\n",np.insert(x,(2,3),500,axis=1))  # Inserting single value on multiple indices

Original:
 [[ 2  4  7  1]
 [ 9 11  5  3]]
Modified:
 [[  2 100   4   7   1]
 [  9 200  11   5   3]]
Modified:
 [[  2   4 101   7 202   1]
 [  9  11 101   5 202   3]]
Modified:
 [[  2   4 500   7 500   1]
 [  9  11 500   5 500   3]]


In [5]:
A = np.arange(1,11)              # Using "append()" function
print("Original:",a)
print("Modified:",np.append(a,55))
print("Modified:",np.append(a,(100,800)))

x = np.array([[2,4,7,1],[9,11,5,3]])
print("Modified:",np.append(x,55))


Original: [ 1  2  3  4  5  6  7  8  9 10]
Modified: [ 1  2  3  4  5  6  7  8  9 10 55]
Modified: [  1   2   3   4   5   6   7   8   9  10 100 800]
Modified: [ 2  4  7  1  9 11  5  3 55]


**Numpy "Deletion":-**

In [6]:
a = np.arange(10,21)
print("Original:",a)

print("Modified:",np.delete(a,4))
print("Original:",a)

x = np.array([[2,4,7,1],[9,11,5,3]])
print("Array:\n",x)
print("Modified:",np.delete(x,3))

Original: [10 11 12 13 14 15 16 17 18 19 20]
Modified: [10 11 12 13 15 16 17 18 19 20]
Original: [10 11 12 13 14 15 16 17 18 19 20]
Array:
 [[ 2  4  7  1]
 [ 9 11  5  3]]
Modified: [ 2  4  7  9 11  5  3]
