# Creating Array

In [1]:
import numpy as np

In [2]:
np.ones((3,5),dtype=np.float32)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [3]:
np.zeros((3,2),dtype=np.int8)


array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [4]:
np.arange(100,110,2)

array([100, 102, 104, 106, 108])

In [5]:
x = np.array([1.3,34,56.3,22.6,10.0])
print(x)
x = x.astype(int)
print(x)
x = x.astype(str)
print(x)

[ 1.3 34.  56.3 22.6 10. ]
[ 1 34 56 22 10]
['1' '34' '56' '22' '10']


In [6]:
A = np.ones((3,1))
B = np.zeros((3,2))
np.concatenate([A,B],axis=1)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [7]:
p= np.array([[1,2,3],[4,5,6]])
q =np.ones_like(p)
r =np.zeros_like(p)
print(p)
print(q)
print(r)


[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [8]:
np.random.random((3,2))

array([[0.4004891 , 0.24435973],
       [0.42859879, 0.91849571],
       [0.64043011, 0.70513546]])