In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,30],[4,15,6],[13,5,6]])
x

array([[ 1,  2, 30],
       [ 4, 15,  6],
       [13,  5,  6]])

In [3]:
np.sqrt(x)

array([[1.        , 1.41421356, 5.47722558],
       [2.        , 3.87298335, 2.44948974],
       [3.60555128, 2.23606798, 2.44948974]])

In [4]:
x.sum()

82

In [5]:
np.where(x>10)

(array([0, 1, 2], dtype=int64), array([2, 1, 0], dtype=int64))

In [6]:
type(np.where(x>10))

tuple

In [7]:
np.count_nonzero(x)     # Gives the count of non-zero elements of Array

9

In [8]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [9]:
x[1,2]=0
np.nonzero(x)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [10]:
x.tolist()            # Converts a Numpy Array to List

[[1, 2, 30], [4, 15, 0], [13, 5, 6]]

In [11]:
import sys

In [12]:
py_ar =[21,4,64,10]

In [13]:
np_ar = np.array(py_ar)

In [14]:
sys.getsizeof(1)* len(py_ar)

112

In [15]:
np_ar.itemsize * np_ar.size

16