## Universal Functions

In [1]:
import numpy as np

**"Unary Universal Functions" :-**

In [2]:
a = np.arange(11)
print("Actual Array:",a)

Actual Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
print("Square value:",np.square(a))
a = np.sqrt(a)
print("New array:\n",a)

Square value: [  0   1   4   9  16  25  36  49  64  81 100]
New array:
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


In [4]:
print("Absolute value:-\n",np.abs(a))
print("Log value:-\n",np.log1p(a))     # Base(e)

Absolute value:-
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
Log value:-
 [0.         0.69314718 0.88137359 1.00505254 1.09861229 1.17435901
 1.23822632 1.29356247 1.34245405 1.38629436 1.42606244]


In [5]:
print("Ceiling value:",np.ceil(a))
print("Floor value:",np.floor(a)) 
print("Sign value:",np.sign(a)) 

Ceiling value: [0. 1. 2. 2. 2. 3. 3. 3. 3. 3. 4.]
Floor value: [0. 1. 1. 1. 2. 2. 2. 2. 2. 3. 3.]
Sign value: [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
print("Rint value:-",np.rint(a)) 
print("Modf value:-\n",np.modf(a)) 

Rint value:- [0. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]
Modf value:-
 (array([0.        , 0.        , 0.41421356, 0.73205081, 0.        ,
       0.23606798, 0.44948974, 0.64575131, 0.82842712, 0.        ,
       0.16227766]), array([0., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3.]))


In [7]:
print("IsNan value:-",np.isnan(a)) 
print("Isfinite value:-",np.isfinite(a)) 
print("Isinfinite value:-",np.isinf(a)) 

IsNan value:- [False False False False False False False False False False False]
Isfinite value:- [ True  True  True  True  True  True  True  True  True  True  True]
Isinfinite value:- [False False False False False False False False False False False]


In [8]:
print("Sin value:-\n",np.sin(a))
print("Hyperbolic sin value:-\n",np.sinh(a))
print("Inverse tan value:-\n",np.arctan(a))

Sin value:-
 [ 0.          0.84147098  0.98776595  0.98702664  0.90929743  0.78674913
  0.63815764  0.47577184  0.30807174  0.14112001 -0.02068353]
Hyperbolic sin value:-
 [ 0.          1.17520119  1.93506682  2.73765623  3.62686041  4.62479555
  5.74804878  7.01153904  8.42986147 10.01787493 11.79100685]
Inverse tan value:-
 [0.         0.78539816 0.95531662 1.04719755 1.10714872 1.15026199
 1.18319964 1.2094292  1.23095942 1.24904577 1.26451896]


**"Binary Universal Functions" :-**

In [9]:
A = np.arange(6,16,1)
B = np.arange(1,20,2)
print("Array A:",A) 
print("Array B:",B) 

Array A: [ 6  7  8  9 10 11 12 13 14 15]
Array B: [ 1  3  5  7  9 11 13 15 17 19]


In [10]:
print("Adding elements from both:",np.add(A,B))
print("Dividing elements from both:",np.floor_divide(A,B))

Adding elements from both: [ 7 10 13 16 19 22 25 28 31 34]
Dividing elements from both: [6 2 1 1 1 1 0 0 0 0]


In [11]:
print("Maximum elements from both:",np.maximum(A,B))
print("Minimum elements from both:",np.minimum(A,B))

Maximum elements from both: [ 6  7  8  9 10 11 13 15 17 19]
Minimum elements from both: [ 1  3  5  7  9 11 12 13 14 15]


In [12]:
print("Multiplying elements from both:",np.multiply(A,B))
print("Power:\n",np.power(A,B))    # Elements of 'A' are raised to power of elements of 'B'

Multiplying elements from both: [  6  21  40  63  90 121 156 195 238 285]
Power:
 [         6        343      32768    4782969 1000000000 1843829075
 1275068416 1788720133 -586285056  198698543]


In [13]:
print("Mod:",np.mod(A,B))     # Gives remainder when elements of 'A' are divided by elements of 'B'
print("Copysign:",np.copysign(A,B))   

Mod: [ 0  1  3  2  1  0 12 13 14 15]
Copysign: [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [14]:
X = np.arange(6, -6 , -1)
Y = np.arange(6, -18 , -2)
print(X)
print(Y)

[ 6  5  4  3  2  1  0 -1 -2 -3 -4 -5]
[  6   4   2   0  -2  -4  -6  -8 -10 -12 -14 -16]


In [15]:
print("Copysign:",np.copysign(X,Y))     # Put sign of second argument to first argument
print("Copysign:",np.copysign(Y,X))     

Copysign: [ 6.  5.  4.  3. -2. -1. -0. -1. -2. -3. -4. -5.]
Copysign: [  6.   4.   2.   0.   2.   4.   6.  -8. -10. -12. -14. -16.]


In [16]:
F = np.arange(6, -6 , -1).reshape((3,4))
G = np.arange(6, -18 , -2).reshape((3,4))
print(F)
print(G)

[[ 6  5  4  3]
 [ 2  1  0 -1]
 [-2 -3 -4 -5]]
[[  6   4   2   0]
 [ -2  -4  -6  -8]
 [-10 -12 -14 -16]]


In [17]:
print("Copysign:\n",np.copysign(F,G))     # Put sign of second argument to first argument
print("Copysign:\n",np.copysign(G,F))

Copysign:
 [[ 6.  5.  4.  3.]
 [-2. -1. -0. -1.]
 [-2. -3. -4. -5.]]
Copysign:
 [[  6.   4.   2.   0.]
 [  2.   4.   6.  -8.]
 [-10. -12. -14. -16.]]
