In [1]:
import numpy as np
array1 = np.array([[3,2,0,7,0],[1,2,3,4,5]])
print(array1)    # Creating an Array using "Numpy".

[[3 2 0 7 0]
 [1 2 3 4 5]]


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros(5)       # Creating an Array with only zeros.

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((4,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(6)      # Creating an Array with only 1s.

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.ones(6).dtype

dtype('float64')

In [8]:
np.empty((4,3))  
# It can have zeros & garbage values as well. Differrent from np.zeros().

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array1*2

array([[ 6,  4,  0, 14,  0],
       [ 2,  4,  6,  8, 10]])

In [10]:
array1+10

array([[13, 12, 10, 17, 10],
       [11, 12, 13, 14, 15]])

In [11]:
array1*array1

array([[ 9,  4,  0, 49,  0],
       [ 1,  4,  9, 16, 25]])

In [12]:
print(array1**3)
print((3*array1) - array1)

[[ 27   8   0 343   0]
 [  1   8  27  64 125]]
[[ 6  4  0 14  0]
 [ 2  4  6  8 10]]


In [13]:
array2 = ([12,3,34,65,76,80])
arr = array2[2:5]             # Slicing an Array.
print(arr)
arr[1]=100
print(array2)

[34, 65, 76]
[12, 3, 34, 65, 76, 80]


In [14]:
array3 = ([12,3,34,65,76,80])
a = array3[2:5].copy()
print(a)
a[1]=100
print(a)

[34, 65, 76]
[34, 100, 76]


In [15]:
print(array1)
print(array1[0,3])       

[[3 2 0 7 0]
 [1 2 3 4 5]]
7
